import type { ShopProductItem } from "./types";

const PRODUCT_IMAGE =
  "https://res.cloudinary.com/ngocxxu/image/upload/v1772070687/paracord/ewbw3koxkwpezgf9hm95.png";

export const SHOP_PRODUCTS: ShopProductItem[] = [
  {
    id: "cobra",
    slug: "cobra-weave",
    titleKey: "cobra",
    descriptionKey: "cobra",
    price: "120.000 ₫",
    priceNum: 120000,
    imageSrc: PRODUCT_IMAGE,
    imageAlt: "Paracord keychain",
    badge: "bestseller",
    colorSwatches: ["#FF5E00", "#332F2C", "#4B5320"],
    category: "bracelets",
    cordType: "550",
    weaveType: "cobra",
    filterColors: ["orange", "black", "green"],
  },
  {
    id: "hkSnapLanyard",
    slug: "hk-snap-lanyard",
    titleKey: "hkSnapLanyard",
    descriptionKey: "hkSnapLanyard",
    price: "80.000 ₫",
    priceNum: 80000,
    imageSrc: PRODUCT_IMAGE,
    imageAlt: "Paracord keychain",
    colorSwatches: ["#DC2626", "#2563EB"],
    category: "lanyards",
    cordType: "550",
    filterColors: ["red", "blue"],
  },
  {
    id: "titanSurvivalCord",
    slug: "titan-survival-cord",
    titleKey: "titanSurvivalCord",
    descriptionKey: "titanSurvivalCord",
    price: "150.000 ₫",
    priceNum: 150000,
    imageSrc: PRODUCT_IMAGE,
    imageAlt: "Paracord keychain",
    badge: "limited",
    colorSwatches: ["#4B5320", "#FF5E00", "#2563EB"],
    category: "keychains",
    cordType: "titan",
    filterColors: ["green", "orange", "blue"],
  },
  {
    id: "monkeyFistKeyfob",
    slug: "monkey-fist-keyfob",
    titleKey: "monkeyFistKeyfob",
    descriptionKey: "monkeyFistKeyfob",
    price: "60.000 ₫",
    priceNum: 60000,
    imageSrc: PRODUCT_IMAGE,
    imageAlt: "Paracord keychain",
    colorSwatches: ["#2563EB", "#6B7280"],
    category: "keychains",
    cordType: "550",
    filterColors: ["blue", "brown"],
  },
  {
    id: "k9TacticalCollar",
    slug: "k9-tactical-collar",
    titleKey: "k9TacticalCollar",
    descriptionKey: "k9TacticalCollar",
    price: "190.000 ₫",
    priceNum: 190000,
    imageSrc: PRODUCT_IMAGE,
    imageAlt: "Paracord keychain",
    colorSwatches: ["#4B5320", "#78350f"],
    category: "petGear",
    cordType: "550",
    filterColors: ["green", "brown"],
  },
  {
    id: "tacticalWatchStrap",
    slug: "tactical-watch-strap",
    titleKey: "tacticalWatchStrap",
    descriptionKey: "tacticalWatchStrap",
    price: "100.000 ₫",
    priceNum: 100000,
    imageSrc: PRODUCT_IMAGE,
    imageAlt: "Paracord keychain",
    colorSwatches: ["#6B7280", "#FFFFFF"],
    category: "bracelets",
    cordType: "550",
    weaveType: "fishtail",
    filterColors: ["white", "black"],
  },
];

export const FILTER_COLORS: { id: string; hex: string }[] = [
  { id: "red", hex: "#DC2626" },
  { id: "orange", hex: "#FF5E00" },
  { id: "blue", hex: "#2563EB" },
  { id: "yellow", hex: "#EAB308" },
  { id: "green", hex: "#4B5320" },
  { id: "white", hex: "#FFFFFF" },
  { id: "black", hex: "#332F2C" },
  { id: "brown", hex: "#78350f" },
];

export const PRICE_MIN = 10_000;
export const PRICE_MAX = 200_000;
export const PRICE_STEP = 10_000;
export const PRODUCTS_PER_PAGE = 9;
